<a href="https://colab.research.google.com/github/Elkopo/gantt/blob/master/UAPR_to_Schedule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import re
from datetime import datetime, timedelta
from dateutil import parser
# import calendar
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

In [3]:
path = "drive/MyDrive/Colab Notebooks/Base_Schedule"
os.chdir(path)
os.listdir()

['base_sched.csv',
 'base_sched_simple.csv',
 'base_sched_v2.xlsx',
 'base_sched_excel.xlsx']

In [4]:
try:
  start_date = datetime.strptime(input("Choose a start date (DD-MMM-YY): "), "%d-%b-%y")
  print(start_date)
except :
  print("Not a parsable date!  Enter in DD-MMM-YYYY format.")

Choose a start date (DD-MMM-YY): 30-SEP-22
2022-09-30 00:00:00

In [5]:
start_date

datetime.datetime(2022, 9, 30, 0, 0)

In [6]:
end_date = start_date + timedelta(days=90)

In [7]:
end_date

datetime.datetime(2022, 12, 29, 0, 0)

In [8]:
cal = calendar()
holidays = cal.holidays(start=start_date, end=end_date)
holidays

DatetimeIndex(['2022-10-10', '2022-11-11', '2022-11-24', '2022-12-26'], dtype='datetime64[ns]', freq=None)

In [9]:
df = pd.read_excel('base_sched_excel.xlsx', parse_dates=True)
# df1 = df.dropna(how='all')
df['Day2'] = df['Day'].astype('int').shift(1)
df['Day2'][0] = 1
df.head(40)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Day,Date,Start_Time,End_Time,Group,Module_POI,Lesson_Activity,Description,Task_ Notes,Resources,Trainers,Uniform,Type,Day2
0,1.0,NaN,08:15:00,08:30:00,3B-352S-22-005,Module B,52S1B01INTRO,Group Resume Activity,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,PPN,1.0
1,1.0,NaN,08:30:00,10:00:00,3B-352S-22-005,Module B,52S1B01LSA01,Integrate into a New Unit/Class,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0
2,1.0,NaN,10:00:00,11:00:00,3B-352S-22-005,Module B,52S1B01LSA02,Describe SIGINT Intelligence Oversight,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0
3,1.0,NaN,11:00:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA06,Discuss Military Briefing for SIGINT Operations,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0
4,1.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,1.0,NaN,13:30:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSA07,Prepare a SIGINT Enterprise Brief,Assign Task,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,IN,1.0
6,2.0,NaN,08:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA07,Prepare a SIGINT Enterprise Brief,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,IN,1.0
7,2.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,2.0
8,2.0,NaN,13:30:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSA07,Prepare a SIGINT Enterprise Brief,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,IN,2.0
9,3.0,NaN,08:30:00,09:30:00,3B-352S-22-005,Module B,52S1B01LSA07,Prepare a SIGINT Enterprise Brief,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,IN,2.0
10,3.0,NaN,09:30:00,10:30:00,3B-352S-22-005,Module B,52S1B01LSA08,PE - Deliver a SIGINT Enterprise Brief,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,PE,3.0
11,3.0,NaN,10:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA03,Describe Staff Operations,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,3.0
12,3.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,3.0
13,3.0,NaN,13:30:00,15:30:00,3B-352S-22-005,Module B,52S1B01LSA04,Discuss Military Writing in Staff Documents,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,3.0
14,3.0,NaN,15:30:00,16:00:00,3B-352S-22-005,Module B,52S1B01LSA05,PE - Write a Signal Survey Team Mission Statement,NaN,Rowe Rm 150B,CW3 Kopas,OCP,PE,3.0
15,3.0,NaN,16:00:00,17:00:00,3B-352S-22-005,Module B,52S1B01LSA10,Describe the USSID Process,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,3.0
16,3.0,NaN,17:00:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSAINTRO,Write Personal Introduction Information Paper,Assignment Due by Midnight,Rowe Rm 150B,CW3 Kopas,OCP,PE,3.0
17,4.0,NaN,08:30:00,10:30:00,3B-352S-22-005,Module B,52S1B01LSA11,PE - Identify Assigned USSIDS,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,PE,3.0
18,4.0,NaN,10:30:00,11:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Introduction to GATEKEEPER (TOOL1200),Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
19,4.0,NaN,11:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Classification Basics (CLAS1000),Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
20,4.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,4.0
21,4.0,NaN,13:30:00,15:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Classification and Marking Mechanics ...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
22,4.0,NaN,15:30:00,16:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Intelligence Oversight Training (OVSC...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
23,4.0,NaN,16:30:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Overview of Signals Intelligence Auth...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
24,5.0,NaN,08:30:00,09:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Intermediate Classification Principle...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,4.0
25,5.0,NaN,09:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - USSID 18 (OVSC1800),Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,5.0
26,5.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,5.0
27,5.0,NaN,13:30:00,15:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - GCHQ Operational Legalities for Five ...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,5.0
28,5.0,NaN,15:30:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - Intelligence Oversight Officer (IOO) ...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,5.0
29,6.0,NaN,08:30:00,10:30:00,3B-352S-22-005,Module B,52S1B01LSA09,VUport - NSA Raw Traffic Database Auditor Trai...,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,IMI,5.0
30,6.0,NaN,10:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA12,Discuss National SIGINT Databases,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,6.0
31,6.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,6.0
32,6.0,NaN,13:30:00,15:00:00,3B-352S-22-005,Module B,52S1B01LSA13,PE - Identify Relevant National SIGINT EKBs,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,PE,6.0
33,7.0,NaN,07:00:00,08:30:00,3B-352S-22-005,Module B,52S1B05LSA01,ACO / ATCAE Brief,Guest Speaker,Rowe Rm 150B,CW3 Kopas,OCP,SE,6.0
34,7.0,NaN,08:30:00,09:30:00,3B-352S-22-005,Module B,52S1B01LSA14,Describe the SIGINT Concept of Operations,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,7.0
35,7.0,NaN,09:30:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA15,Create a SIGINT Concept of Operations,NaN,Rowe Rm 150B,CW3 Kopas,OCP,PE,7.0
36,7.0,NaN,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,7.0
37,7.0,NaN,13:30:00,15:30:00,3B-352S-22-005,Module B,52S1B01LSA15,PE - Create a SIGINT Concept of Operations,Assignment Due,Rowe Rm 150B,CW3 Kopas,OCP,PE,7.0
38,7.0,NaN,16:30:00,17:00:00,3B-352S-22-005,Module B,52S1B01LSA16,Write a Signal of Interest Executive Summary (...,Assign Task,Rowe Rm 150B,CW3 Kopas,OCP,TE,7.0
39,7.0,NaN,17:00:00,17:30:00,3B-352S-22-005,Module B,52S1B01LSA17,Prepare Signal of Interest Brief #1,Assign Task,Rowe Rm 150B,CW3 Kopas,OCP,IN,7.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Day              174 non-null    float64
 1   Date             0 non-null      float64
 2   Start_Time       174 non-null    object
 3   End_Time         174 non-null    object
 4   Group            174 non-null    object
 5   Module_POI       174 non-null    object
 6   Lesson_Activity  174 non-null    object
 7   Description      137 non-null    object
 8   Task_ Notes      43 non-null     object
 9   Resources        136 non-null    object
 10  Trainers         132 non-null    object
 11  Uniform          127 non-null    object
 12  Type             134 non-null    object
 13  Day2             174 non-null    float64
dtypes: float64(3), object(11)
memory usage: 19.2+ KB

In [11]:
temp_date = start_date
# temp_date = datetime.strptime(, "%d-%b-%y")
df['Date'] = pd.to_datetime(df['Date'])
# df['End_Time'] = pd.to_datetime(df['End_Time'], format='%H:%M:%S').apply(pd.Timestamp)
# df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%H:%M:%S').apply(pd.Timestamp)
df['Hours'] = df['End_Time'] - df['Start_Time']

TypeError: ignored

In [19]:
df

,Day,Date,Start_Time,End_Time,Group,Module_POI,Lesson_Activity,Description,Task_ Notes,Resources,Trainers,Uniform,Type,Day2,Hours
0,1.0,NaT,1900-01-01 08:15:00,1900-01-01 08:30:00,3B-352S-22-005,Module B,52S1B01INTRO,Group Resume Activity,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,PPN,1.0,0 days 00:15:00
1,1.0,NaT,1900-01-01 08:30:00,1900-01-01 10:00:00,3B-352S-22-005,Module B,52S1B01LSA01,Integrate into a New Unit/Class,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
2,1.0,NaT,1900-01-01 10:00:00,1900-01-01 11:00:00,3B-352S-22-005,Module B,52S1B01LSA02,Describe SIGINT Intelligence Oversight,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:00:00
3,1.0,NaT,1900-01-01 11:00:00,1900-01-01 12:30:00,3B-352S-22-005,Module B,52S1B01LSA06,Discuss Military Briefing for SIGINT Operations,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
4,1.0,NaT,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0 days 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,37.0,NaT,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Module B,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,37.0,0 days 01:00:00
170,37.0,NaT,1900-01-01 13:30:00,1900-01-01 16:00:00,3B-352S-22-005,Module B,52S1B06LSA06,Prepare Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,IN,37.0,0 days 02:30:00
171,37.0,NaT,1900-01-01 16:00:00,1900-01-01 17:00:00,3B-352S-22-005,Module B,52S1B06LSA07,Deliver Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 01:00:00
172,37.0,NaT,1900-01-01 17:00:00,1900-01-01 17:15:00,3B-352S-22-005,Module B,52S1B06SUM,TLO Summary,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,37.0,0 days 00:15:00
173,37.0,NaT,1900-01-01 17:15:00,1900-01-01 17:30:00,3B-352S-22-005,Module B,52S1B06LSA07,Write Emerging Technology Information Paper,Assignment Due by Midnight,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 00:15:00

In [33]:
def format_dates(dfx, tempDate):
  if dfx['Day'] == dfx['Day2']:
    dfx['Date'] = tempDate
  else:
    tempDate = tempDate + pd.offsets.Day(1)
    dfx['Date'] = tempDate
  return dfx
    

df2 = df.apply(format_dates, axis=1, tempDate=temp_date)

In [34]:
df2

,Day,Date,Start_Time,End_Time,Group,Module_POI,Lesson_Activity,Description,Task_ Notes,Resources,Trainers,Uniform,Type,Day2,Hours
0,1.0,2022-11-05,1900-01-01 08:15:00,1900-01-01 08:30:00,3B-352S-22-005,Module B,52S1B01INTRO,Group Resume Activity,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,PPN,1.0,0 days 00:15:00
1,1.0,2022-11-05,1900-01-01 08:30:00,1900-01-01 10:00:00,3B-352S-22-005,Module B,52S1B01LSA01,Integrate into a New Unit/Class,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
2,1.0,2022-11-05,1900-01-01 10:00:00,1900-01-01 11:00:00,3B-352S-22-005,Module B,52S1B01LSA02,Describe SIGINT Intelligence Oversight,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:00:00
3,1.0,2022-11-05,1900-01-01 11:00:00,1900-01-01 12:30:00,3B-352S-22-005,Module B,52S1B01LSA06,Discuss Military Briefing for SIGINT Operations,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
4,1.0,2022-11-05,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0 days 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,37.0,2022-11-05,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Module B,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,37.0,0 days 01:00:00
169,37.0,2022-11-05,1900-01-01 13:30:00,1900-01-01 16:00:00,3B-352S-22-005,Module B,52S1B06LSA06,Prepare Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,IN,37.0,0 days 02:30:00
170,37.0,2022-11-05,1900-01-01 16:00:00,1900-01-01 17:00:00,3B-352S-22-005,Module B,52S1B06LSA07,Deliver Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 01:00:00
171,37.0,2022-11-05,1900-01-01 17:00:00,1900-01-01 17:15:00,3B-352S-22-005,Module B,52S1B06SUM,TLO Summary,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,37.0,0 days 00:15:00
172,37.0,2022-11-05,1900-01-01 17:15:00,1900-01-01 17:30:00,3B-352S-22-005,Module B,52S1B06LSA07,Write Emerging Technology Information Paper,Assignment Due by Midnight,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 00:15:00

In [18]:
for i, row in df.iterrows():
  #if temp_date.isin(holidays):
  if row['Day'] == int(row['Day2']):
    row['Date'] = temp_date
    df['Date'][i] = row['Date']
  else:
    temp_date = temp_date + pd.offsets.Day(1)
    row['Date'] = temp_date
    df['Date'][i] = row['Date']

df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Day,Date,Start_Time,End_Time,Group,Module_POI,Lesson_Activity,Description,Task_ Notes,Resources,Trainers,Uniform,Type,Day2,Hours
0,1.0,2022-09-30,1900-01-01 08:15:00,1900-01-01 08:30:00,3B-352S-22-005,Module B,52S1B01INTRO,Group Resume Activity,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,PPN,1.0,0 days 00:15:00
1,1.0,2022-09-30,1900-01-01 08:30:00,1900-01-01 10:00:00,3B-352S-22-005,Module B,52S1B01LSA01,Integrate into a New Unit/Class,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
2,1.0,2022-09-30,1900-01-01 10:00:00,1900-01-01 11:00:00,3B-352S-22-005,Module B,52S1B01LSA02,Describe SIGINT Intelligence Oversight,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:00:00
3,1.0,2022-09-30,1900-01-01 11:00:00,1900-01-01 12:30:00,3B-352S-22-005,Module B,52S1B01LSA06,Discuss Military Briefing for SIGINT Operations,NaN,Rowe Rm 150,CW3 Kopas/CW3 Olivares,OCP,DSL,1.0,0 days 01:30:00
4,1.0,2022-09-30,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0 days 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,37.0,2022-11-05,1900-01-01 12:30:00,1900-01-01 13:30:00,3B-352S-22-005,Module B,Lunch,NaN,NaN,NaN,NaN,NaN,NaN,37.0,0 days 01:00:00
169,37.0,2022-11-05,1900-01-01 13:30:00,1900-01-01 16:00:00,3B-352S-22-005,Module B,52S1B06LSA06,Prepare Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,IN,37.0,0 days 02:30:00
170,37.0,2022-11-05,1900-01-01 16:00:00,1900-01-01 17:00:00,3B-352S-22-005,Module B,52S1B06LSA07,Deliver Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 01:00:00
171,37.0,2022-11-05,1900-01-01 17:00:00,1900-01-01 17:15:00,3B-352S-22-005,Module B,52S1B06SUM,TLO Summary,NaN,Rowe Rm 150B,CW3 Kopas,OCP,DSL,37.0,0 days 00:15:00
172,37.0,2022-11-05,1900-01-01 17:15:00,1900-01-01 17:30:00,3B-352S-22-005,Module B,52S1B06LSA07,Write Emerging Technology Information Paper,Assignment Due by Midnight,Rowe Rm 150B,CW3 Kopas,OCP,TE,37.0,0 days 00:15:00

In [19]:
df = df.drop(columns='Day2')

In [20]:
df_test = df.copy()
df_test['DayofWeek'] = df_test['Date'].dt.weekday
df_test

,Day,Date,Start_Time,End_Time,Group,Module_POI,Lesson_Activity,Description,Task_ Notes,Resources,Trainers,Uniform,Hours,Type,DayofWeek
0,1.0,2022-09-30,08:15:00,08:30:00,3B-352S-22-005,Module B,52S1B01INTRO,Group Resume Activity,NaN,Rowe Rm 150B,CW3 Kopas,OCP,00:15:00,PPN,4
1,1.0,2022-09-30,08:30:00,10:00:00,3B-352S-22-005,Module B,52S1B01LSA01,Integrate into a New Unit/Class,NaN,Rowe Rm 150B,CW3 Kopas,OCP,01:30:00,DSL,4
2,1.0,2022-09-30,10:00:00,11:00:00,3B-352S-22-005,Module B,52S1B01LSA02,Describe SIGINT Intelligence Oversight,NaN,Rowe Rm 150B,CW3 Kopas,OCP,01:00:00,DSL,4
3,1.0,2022-09-30,11:00:00,12:30:00,3B-352S-22-005,Module B,52S1B01LSA06,Discuss Military Briefing for SIGINT Operations,NaN,Rowe Rm 150B,CW3 Kopas,OCP,01:30:00,DSL,4
4,1.0,2022-09-30,12:30:00,13:30:00,3B-352S-22-005,Admin,Lunch,NaN,NaN,NaN,NaN,NaN,01:00:00,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,37.0,2022-11-05,12:30:00,13:30:00,3B-352S-22-005,Module B,Lunch,NaN,NaN,NaN,NaN,NaN,01:00:00,NaN,5
172,37.0,2022-11-05,13:30:00,16:00:00,3B-352S-22-005,Module B,52S1B06LSA06,Prepare Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,02:30:00,IN,5
173,37.0,2022-11-05,16:00:00,17:00:00,3B-352S-22-005,Module B,52S1B06LSA07,Deliver Emerging Technology Brief #5,NaN,Rowe Rm 150B,CW3 Kopas,OCP,01:00:00,TE,5
174,37.0,2022-11-05,17:00:00,17:15:00,3B-352S-22-005,Module B,52S1B06SUM,TLO Summary,NaN,Rowe Rm 150B,CW3 Kopas,OCP,00:15:00,DSL,5
175,37.0,2022-11-05,17:15:00,17:30:00,3B-352S-22-005,Module B,52S1B06LSA07,Write Emerging Technology Information Paper,Assignment Due by Midnight,Rowe Rm 150B,CW3 Kopas,OCP,00:15:00,TE,5

In [ ]:
days_of_week = {0 : 'Monday', 1 : "Tuesday", 2 : "Wednesday", 3 : 'Thursday', 4 : "Friday"}
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Day              176 non-null    int64
 1   Date             176 non-null    datetime64[ns]
 2   Start_Time       176 non-null    object
 3   End_Time         176 non-null    object
 4   Group            176 non-null    object
 5   Module_POI       176 non-null    object
 6   Lesson_Activity  176 non-null    object
 7   Description      139 non-null    object
 8   Task_ Notes      43 non-null     object
 9   Resources        142 non-null    object
 10  Trainers         131 non-null    object
 11  Uniform          120 non-null    object
 12  Hours            176 non-null    object
 13  Type             137 non-null    object
 14  DayofWeek        176 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(12)
memory usage: 20.8+ KB

In [ ]:
# test = pd.to_datetime(df4['Time'], format="%A, %B %d, %Y")
# re.match(r'\w, \w, \d{1,2}, \d{4}'), df4['Time']
def date_check(dc):
  if re.search(r'\b(Mon|Tues|Wednes|Thurs|Fri|Satur|Sun)(day)\, \w{4,9} \d{1,2}\, \d{4}', str(dc)):
    return dc
  else:
    return np.nan

In [ ]:
df4['Date'] = df4['Time'].apply(date_check)
df4['Date'] = df4['Date'].ffill()
df4['Date'] = pd.to_datetime(df4['Date'])

In [ ]:
#df5 = df4[df4['Time'] != str(np.nan)]
#df6 = df5[df5['Time']]
df5 = df4.dropna(subset=['Lesson_Title'])
# df5

In [ ]:
df5['Training_Day'] = range(1,len(df5)+1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df6 = df5.assign(Training_Day=(df5['Date'] != df5['Date'].shift(periods=1, axis=0)).cumsum())
df6.set_index(['Training_Day', 'Date'], inplace=True)
# df5.index.duplicated(keep='last')

In [ ]:
df6.iloc

                                Time Organization Module_POI  PFN  \
Training_Day Date
1            2022-07-12  0530 - 1200  B Co, 304th   Module A  NaN
             2022-07-12  1200 - 1700  B Co, 304th   Module A  NaN
2            2022-07-13  0800 - 0900  B Co, 304th   Module A  NaN
             2022-07-13  0900 - 1200  B Co, 304th        NaN  NaN
             2022-07-13  1300 - 1715  B Co, 304th        NaN  NaN
...                              ...          ...        ...  ...
64           2022-10-13  1300 - 1700  B Co, 304th   Module A  NaN
65           2022-10-14  0800 - 0900  B Co, 304th   Module A  NaN
             2022-10-14  0900 - 1000  B Co, 304th   Module A  NaN
             2022-10-14  1000 - 1215  B Co, 304th   Module A  NaN
             2022-10-14  1300 - 1515  B Co, 304th   Module A  NaN

                              Lesson_Title        Description  \
Training_Day Date
1            2022-07-12  WOBC Course Admin  WOBC Course Admin
             2022-07-12  WOBC Course Admin  WOBC Course Admin
2            2022-07-13  WOBC Course Admin        SSO Read On
             2022-07-13  WOBC Course Admin                NaN
             2022-07-13  WOBC Course Admin                NaN
...                                    ...                ...
64           2022-10-13  WOBC Course Admin     Out Processing
65           2022-10-14  WOBC Course Admin     Out Processing
             2022-10-14  WOBC Course Admin         Graduation
             2022-10-14  WOBC Course Admin    Close Out Admin
             2022-10-14  WOBC Course Admin    Close Out Admin

                                    Resources  Uni Hours             Notes  \
Training_Day Date
1            2022-07-12  Nicholson Rm 136/140  ACU  6.50               NaN
             2022-07-12  Nicholson Rm 136/140  ACU  5.00               NaN
2            2022-07-13         Friedman Hall  ACU  1.00  scheduled by G37
             2022-07-13           Rowe Rm 234  ACU  3.00               NaN
             2022-07-13           Rowe Rm 234  ACU  4.25               NaN
...                                       ...  ...   ...               ...
64           2022-10-13           Rowe Rm 234  ACU  4.00               NaN
65           2022-10-14           Rowe Rm 234  ACU  1.00               NaN
             2022-10-14           Rowe Rm 234  ACU  1.00               NaN
             2022-10-14           Rowe Rm 234  ACU  2.25               NaN
             2022-10-14           Rowe Rm 234  ACU  2.25               NaN

                         Type
Training_Day Date
1            2022-07-12   NaN
             2022-07-12   NaN
2            2022-07-13   NaN
             2022-07-13   NaN
             2022-07-13   NaN
...                       ...
64           2022-10-13   NaN
65           2022-10-14   NaN
             2022-10-14   NaN
             2022-10-14   NaN
             2022-10-14   NaN

[242 rows x 11 columns]